CREATE TABLE XML_AGENTES (
  ID NUMBER PRIMARY KEY,
  XML_CONTEUDO XMLTYPE
);

CREATE SEQUENCE SEQ_XML_AGENTES START WITH 1 INCREMENT BY 1;

/

CREATE TABLE XML_CONTAS_PAGAR (
  ID NUMBER PRIMARY KEY,
  XML_CONTEUDO XMLTYPE
);

CREATE SEQUENCE SEQ_XML_CONTAS_PAGAR START WITH 1 INCREMENT BY 1;
